---

- name: Configurar pi4
  hosts: pi4                # hosts do inventory que se aplica
  become: true                   # sudo

  pre_tasks:
    # apt-get update
    - name: Atualizar cache do apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600  # só atualiza se o cache tiver mais de 1h


  tasks:
    # omada controller
    - name: Instalar dependências do Omada
      ansible.builtin.apt:
        name:
          - openjdk-17-jre-headless
          - jsvc
        state: present

    - name: Baixar pacote do Omada Controller
      ansible.builtin.get_url:
        url: "{{ omada_download_url }}"
        dest: /tmp/omada.deb

    - name: Instalar Omada Controller
      ansible.builtin.apt:
        deb: /tmp/omada.deb
        state: present

    - name: Garantir que o omada está rodando no boot
      ansible.builtin.service:
        name: omada-controller
        state: started
        enabled: true

    # motioneye
    - name: Instalar dependências do MotionEye
      ansible.builtin.apt:
        name:
          - motion
          - python3-pip
          - python3-dev
        state: present

    - name: Instalar MotionEye via pip
      ansible.builtin.pip:
        name: motioneye
        state: present

    - name: Garantir que o motioneye está rodando no boot
      ansible.builtin.service:
        name: motioneye
        state: started
        enabled: true

  # node exporter
    - name: Instalar Node Exporter
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    - name: Garantir que Node Exporter está rodando
      ansible.builtin.service:
        name: prometheus-node-exporter
        state: started
        enabled: true

  # tailscale
    - name: Baixar e rodar o script de instalação do Tailscale
      ansible.builtin.shell:
        cmd: curl -fsSL https://tailscale.com/install.sh | sh
        creates: /usr/bin/tailscale  # idempotência: só roda se o binário ainda não existir

    - name: Conectar ao Tailscale com a auth key
      ansible.builtin.command:
        cmd: tailscale up --authkey="{{ tailscale_auth_key }}"
        creates: /var/lib/tailscale/tailscaled.state  # idem — evita reconectar toda vez

    - name: Garantir que o tailscaled está rodando no boot
      ansible.builtin.service:
        name: tailscaled
        state: started
        enabled: true