---

- name: Configure storage-server
  hosts: storage-server                # hosts do inventory que se aplica
  become: true                         # sudo

  pre_tasks:
    # apt-get update
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600  # só atualiza se o cache tiver mais de 1h

  # nfs
  tasks:
    - name: Install NFS package
      ansible.builtin.apt:
        name:
          - nfs-kernel-server
          - nfs-common
          - btrfs-progs
        state: present

    - name: Create btrfs filesystem on storage device
      community.general.filesystem:
        fstype: btrfs
        dev: "{{ storage_device }}"
        opts: "-L data-sata"
        force: false # não formata se já existir
      when: ansible_mounts | selectattr('device', 'equalto', storage_device) | list | length == 0

    - name: Get UUID of storage device
      ansible.builtin.command:
        cmd: blkid -s UUID -o value {{ storage_device }}
      register: storage_uuid
      changed_when: false

    - name: Mount storage with btrfs options via fstab
      ansible.builtin.mount:
        path: "{{ storage_mount }}"
        src: "UUID={{ storage_uuid.stdout }}"
        fstype: btrfs
        opts: defaults,compress=zstd,noatime
        state: mounted

    - name: Create data directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ nfs_exports }}"

    - name: Config and export with NFS (/etc/exports)
      ansible.builtin.template:
        src: templates/exports.j2
        dest: /etc/exports
      notify: Reload NFS

    - name: Ensure NFS is running and enabled on boot
      ansible.builtin.service:
        name: nfs-kernel-server
        state: started
        enabled: true      

  # node exporter
    - name: Install Node Exporter
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    - name: Ensure Node Exporter is running and enabled on boot
      ansible.builtin.service:
        name: prometheus-node-exporter
        state: started
        enabled: true

  # tailscale
    - name: Download and run Tailscale installation script
      ansible.builtin.shell:
        cmd: curl -fsSL https://tailscale.com/install.sh | sh
        creates: /usr/bin/tailscale  # idempotência: só roda se o binário ainda não existir

    - name: Ensure Tailscale is running and enabled on boot
      ansible.builtin.service:
        name: tailscaled
        state: started
        enabled: true

    - name: Connect to Tailscale with auth key
      ansible.builtin.command:
        cmd: tailscale up --authkey="{{ tailscale_auth_key }}"
      register: tailscale_up
      changed_when: tailscale_up.rc == 0

 # rodam no final se "notify" foi acionado
  handlers:
    - name: Reload NFS
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted

