[proxmox_vms]
k3s-node        ansible_host=10.10.10.11 ansible_user=debian
lxc-monitoring  ansible_host=10.10.10.13 ansible_user=root

[nas]
truenas ansible_host=10.10.10.15 ansible_user=root

[pi4_host]
pi4 ansible_host=10.10.10.14 ansible_user=lfck